<?php
namespace App\Controller;

use Cake\Event\Event;
use Cake\ORM\Query;

/**
 * Disciplines Controller
 *
 * @property \App\Model\Table\DisciplinesTable $Disciplines
 */
class DisciplinesController extends AppController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

        $this->Auth->allow(['index']);
    }

    /**
     * JSON-only
     * Return all disciplines available
     */
    public function index()
    {
        $disciplines = $this->Disciplines->find('list')->toArray();
        $this->set($disciplines);
    }
}
