<?php
namespace App\Controller;

use Cake\Event\Event;
use Cake\ORM\Query;

/**
 * Disciplines Controller
 *
 * @property \App\Model\Table\DisciplinesTable $Disciplines
 */
class DisciplinesController extends AppController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

        $this->Auth->allow(['index', 'byLevel']);
    }

    /**
     * JSON-only
     * Return all disciplines available
     */
    public function index()
    {

    }

    /**
     * JSON-only
     * @param int $levelId
     */
    public function byLevel(int $levelId)
    {
        if ($this->request->is('json')) {
            $this->set(
                $this->Disciplines->find('list')
                    ->matching('Levels', function (Query $q) use ($levelId) {
                        return $q->where(['Levels.id' => $levelId]);
                    })
                    ->toArray()
            );
        }
    }
}
