<?php
namespace App\Controller;

use Cake\Event\Event;

/**
 * Levels Controller
 *
 * @property \App\Model\Table\LevelsTable $Levels
 */
class LevelsController extends AppController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow(['index']);
    }

    /**
     * JSON-only
     * Return all disciplines available
     */
    public function index()
    {
        if ($this->request->is('json')) {
            $this->set($this->Levels->find('list')->toArray());
        }
    }
}
